import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'picsum.photos' },
      { protocol: 'https', hostname: 'wallpapercave.com' },
      { protocol: 'https', hostname: '**.wallpapercave.com' },
      { protocol: 'https', hostname: '**.redd.it' },
      { protocol: 'https', hostname: '**.alphacoders.com' },
      { protocol: 'https', hostname: '**.uhdpaper.com' },
      { protocol: 'https', hostname: 'wallpapers.com' },
      { protocol: 'https', hostname: 'wallpapercat.com' },
      { protocol: 'https', hostname: '**.thegamerimages.com' },
      { protocol: 'https', hostname: '**.gamerantimages.com' },
      { protocol: 'https', hostname: 'getwallpapers.com' },
      { protocol: 'https', hostname: '**.steamstatic.com' },
      { protocol: 'https', hostname: '**.wallpapergap.com' },
      { protocol: 'https', hostname: 'wallpaperaccess.com' },
      { protocol: 'https', hostname: '4kwallpapers.com' },
      { protocol: 'https', hostname: '**.pinimg.com' },
      { protocol: 'https', hostname: 'wallpapercg.com' },
      { protocol: 'https', hostname: '**.wp.com' },
      { protocol: 'https', hostname: '**.ftcdn.net' },
      { protocol: 'https', hostname: '**.displate.com' },
      { protocol: 'https', hostname: '**.wixmp.com' },
      { protocol: 'https', hostname: 'mygamingtutorials.com' },
      { protocol: 'https', hostname: '**.thumbculture.co.uk' },
      { protocol: 'https', hostname: '**.wallpapersafari.com' },
      { protocol: 'https', hostname: '**.contentstack.com' },
      { protocol: 'https', hostname: '**.grimdarkmagazine.com' },
      { protocol: 'https', hostname: '**.squarespace-cdn.com' },
      { protocol: 'https', hostname: '**.earlygamecdn.com' },
      { protocol: 'https', hostname: '**.cloudfront.net' },
      { protocol: 'https', hostname: '**.wccftech.com' },
      { protocol: 'https', hostname: '**.callofduty.com' },
      { protocol: 'https', hostname: '**.media-amazon.com' },
      { protocol: 'https', hostname: '**.playstation.com' },
      { protocol: 'https', hostname: '**.bauerhosting.com' },
      { protocol: 'https', hostname: 'kotaku.com' },
      { protocol: 'https', hostname: '**.futurecdn.net' },
      { protocol: 'https', hostname: '**.cnet.com' },
      { protocol: 'https', hostname: '**.creativeuncut.com' },
      { protocol: 'https', hostname: '**.thqnordic.com' },
      { protocol: 'https', hostname: '**.kojimaproductions.jp' },
      { protocol: 'https', hostname: '**.delivery.rocketcdn.me' },
      { protocol: 'https', hostname: '**.steamusercontent.com' },
      { protocol: 'https', hostname: '**.gamemaps.com' },
      { protocol: 'https', hostname: 'gameinformer.com' },
      { protocol: 'https', hostname: '**.smushcdn.com' },
      { protocol: 'https', hostname: 'twistedvoxel.com' },
      { protocol: 'https', hostname: 'wolfsgamingblog.com' },
      { protocol: 'https', hostname: '**.purexbox.com' },
      { protocol: 'https', hostname: 'travelchinawith.me' },
      { protocol: 'https', hostname: '**.srcdn.com' },
    ],
  },
};

export default nextConfig;
